### ISSUE TITLE
Draging plots in rtkplot_qt and rtknavi_qt

### ISSUE THREAD

**Issue by GPSFan** [JensReimann/RTKLIB#7]
When I have a data set plotted in rtkplot_qt or a ground track in rtknavi_qt clicking on the graph and trying to drag it often results in the graph moving out of the window. It is as if the mouse were being moved excessively. Just clicking and not moving the mouse causes the data to be replotted in the same spot, but moving the mouse even just a few pixels results in the plot moving excessively.
Using the scroll wheel to zoom in and out works as expected in rtkplot_qt, but does not in rtknavi_qt and clicking on the + or - icons does not work either. Dragging and zooming works as expected in the Windows version.

**Comment by JensReimann** [comment]
Hi GPSFan,
the jumps at the beginning of dragging the graph have been fixed in rtkplot_qt as well as the + and - buttons in rtknavi_qt.
Dragging and zooming of the graph is currently not implemented in rtknavi_qt and it should also not work in the Windows version of rtknavi. As it is an expected behavior it may be worth implementing it.

**Comment by GPSFan** [comment]
I assumed it should work in Qt and would work in Windows since there are references to "drag" in both rtknavi_qt/mapdlg and rtknavi/mapdlg. My mistake...
Thanks for fixing the zoom & drag in rtkplot_qt and the + & - buttons in rtknavi.

I was able to cherrypick commits into the rtkexplorer branch without any conflicts, and they compile and at least rtkplot_qt & rtknavi_qt work (I haven't tried the others yet but since they have no changes they should work as before).
